package com.upgrad.movie.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.Set;

@DynamoDBTable(tableName = "PLACEHOLDER_TABLE_NAME")
public class Movie {

    private String movieId;
    private String movieName;
    private String movieDescription;
    private String releaseDate;
    private int durationInMin;
    private String coverPhotoUrl;
    private String trailerUrl;

    public Movie() {
    }

    @DynamoDBHashKey(attributeName = "movieId")
    @DynamoDBAutoGeneratedKey
    public String getMovieId() {
        return movieId;
    }
    public void setMovieId(String movieId) {
        this.movieId = movieId;
    }


    @DynamoDBAttribute(attributeName = "movieName")
    public String getMovieName() {
        return movieName;
    }
    public void setMovieName(String movieName) {
        this.movieName = movieName;
    }

    @DynamoDBAttribute(attributeName = "movieDescription")
    public String getMovieDescription() {
        return movieDescription;
    }
    public void setMovieDescription(String movieDescription) {
        this.movieDescription = movieDescription;
    }

    @DynamoDBAttribute(attributeName = "releaseDate")
    public String getReleaseDate() {
        return releaseDate;
    }
    public void setReleaseDate(String releaseDate) {
        this.releaseDate = releaseDate;
    }

    @DynamoDBAttribute(attributeName = "coverPhotoUrl")
    public String getCoverPhotoUrl() {
        return coverPhotoUrl;
    }
    public void setCoverPhotoUrl(String coverPhotoUrl) {
        this.coverPhotoUrl = coverPhotoUrl;
    }

    @DynamoDBAttribute(attributeName = "durationInMin")
    public int getDurationInMin() {
        return durationInMin;
    }
    public void setDurationInMin(int durationInMin) {
        this.durationInMin = durationInMin;
    }

    @DynamoDBAttribute(attributeName = "trailerUrl")
    public String getTrailerUrl() {
        return trailerUrl;
    }
    public void setTrailerUrl(String trailerUrl) {
        this.trailerUrl = trailerUrl;
    }

}